### ISSUE TITLE
`.gitignore` puzzle input

### ISSUE THREAD

**Issue by ver-nyan** [thermoweb/aoc-java-template#1]
Hi 👋. Awesome template! 🎄

I believe the puzzle inputs `aoc-solutions/src/main/resources/inputs/` should also be added to `.gitignore`.

On another note, would you be interested in adding your template to https://github.com/Bogdanp/awesome-advent-of-code? It would make a great addition since I think this java template is much better than the ones currently listed.

**Comment by thermoweb** [comment]
Hello,

I added the input directory in the gitignore, thanks for this insight.

Also you you can add this template into the awesome aoc, it would be an honnor :)

**Comment by ver-nyan** [comment]
Merged in https://github.com/Bogdanp/awesome-advent-of-code/pull/2024. 😄
